GET http://localhost:9099/dishes

###
POST http://localhost:9099/addDish
Content-Type: application/json

{
    "name": "Tiger Roll",
    "description": "roll con philadelfia, avocado, salmone",
    "category": "primi",
    "price": 5,
    "addedIngredients": "no",
    "photo": "Tiger Roll photo"
}

###

GET http://localhost:9099/users

###

POST http://localhost:9099/addUser
Content-Type: application/json

{
 "firstName": "Paolino",
 "lastName": "Paperino",
    "password": "paolinopaperino",
    "email": "paolino21@yahoo.it",
    "age": 132
    }

###

DELETE http://localhost:9099/deleteUser/661c59af7d4e68c6351e6262